# -*- python -*-
from lsst.sconsUtils import scripts, log

import eups

ignoreList = ["crSplitStagesImSimTest.py", "crSplitStagesTest.py",
        "ioStages.py"]
scripts.BasicSConscript.tests(ignoreList=ignoreList)
