# -*- python -*-
from lsst.sconsUtils import scripts, log

import eups

# Turn off all pex_harness-based tests (which is currently everything)
ignoreList = ["crSplitStagesImSimTest.py", "crSplitStagesTest.py", "ioStages.py", "testGetPsf.py", "testIngestSource.py", "vigCorr.py"]

scripts.BasicSConscript.tests(ignoreList=ignoreList)
